/* RELIC RUN — deterministic continuous third-person runner. */
'use strict';
const $=s=>document.querySelector(s), clamp=(v,a,b)=>Math.max(a,Math.min(b,v)), lerp=(a,b,t)=>a+(b-a)*t;
const ASSETS=window.RELIC_ASSETS||{runner:'assets/runner.glb',environment:'assets/environment.png',monster:'assets/monster.png',reference:'assets/reference.png',stone:'assets/stone.png',facade:'assets/tower-v4.png',stoneDiffuse:'assets/stone-diff.jpg',stoneNormal:'assets/stone-nor_gl.jpg',stoneARM:'assets/stone-arm.jpg',forestLight:'assets/forest-light.hdr',fern:'assets/fern-realistic.png',fireAtlas:'assets/fire-atlas-v5.png'};
const stage=$('#stage'), canvas=$('#game');
let renderer,environmentDetail=null,routeReadability=null;
try{renderer=new THREE.WebGLRenderer({canvas,alpha:true,antialias:true,powerPreference:'high-performance'});}catch(e){$('#loading').textContent='浏览器未开启 3D 图形支持，请使用 Chrome 或 Edge 重试。';throw e;}
renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,1.7));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.04;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;
const scene=new THREE.Scene();scene.fog=new THREE.FogExp2(0xadc3bb,.0105);const camera=new THREE.PerspectiveCamera(57,9/16,.1,240);
scene.add(new THREE.HemisphereLight(0xe1eff4,0x514228,.8));const sun=new THREE.DirectionalLight(0xffe8bd,3.35);sun.position.set(-16,35,15);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-13,right:13,top:22,bottom:-13,near:1,far:90});sun.shadow.bias=-.001;sun.shadow.normalBias=.012;scene.add(sun);scene.add(sun.target);
const fireBounce=new THREE.PointLight(0xff782a,0,13,1.5);scene.add(fireBounce);
const imageLoad=src=>new Promise((resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=reject;i.src=src;});
let seed=9182;function rnd(){seed=(Math.imul(1664525,seed)+1013904223)>>>0;return seed/4294967296;}
function texCanvas(w,h,draw){const c=document.createElement('canvas');c.width=w;c.height=h;draw(c.getContext('2d'),w,h);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t;}
const stone=texCanvas(512,512,(c,w,h)=>{c.fillStyle='#33382c';c.fillRect(0,0,w,h);for(let row=0;row<6;row++)for(let col=-1;col<5;col++){let x=col*128+(row%2)*64,y=row*86,v=78+rnd()*35;c.fillStyle=`rgb(${v+12},${v+11},${v-1})`;c.beginPath();c.roundRect(x+3,y+3,122,80,5+rnd()*6);c.fill();c.strokeStyle='#c9c5a45f';c.lineWidth=2;c.stroke();for(let n=0;n<350;n++){let a=x+rnd()*125,b=y+rnd()*80;c.fillStyle=rnd()>.5?'#e0d8b316':'#19251530';c.fillRect(a,b,rnd()*4+1,rnd()*2+1);}c.strokeStyle='#2b322773';c.lineWidth=1;c.beginPath();c.moveTo(x+23,y+2);c.lineTo(x+43,y+30);c.lineTo(x+37,y+45);c.stroke();}for(let i=0;i<2500;i++){let x=rnd()*w,y=rnd()*h;c.fillStyle=['#2c4428aa','#58603988','#52622d88','#69834977'][i%4];if(i%4===0||x%128<15||y%86<12){c.beginPath();c.arc(x,y,rnd()*5+.5,0,7);c.fill();}}});stone.wrapS=stone.wrapT=THREE.RepeatWrapping;stone.anisotropy=Math.min(renderer.capabilities.getMaxAnisotropy(),8);
const material=(color,extra={})=>new THREE.MeshStandardMaterial({color,roughness:.95,...extra});
const stoneMat=material(0xb6b39a,{map:stone,bumpMap:stone,bumpScale:.09});const darkMat=material(0x696e52,{map:stone,bumpMap:stone,bumpScale:.15});const goldMat=material(0xf2ba42,{metalness:.72,roughness:.3,emissive:0xc27b13,emissiveIntensity:.38});const blackMat=material(0x292e21);const mossMat=material(0x4b6032);const spikeMat=material(0xafa07a,{metalness:.5,roughness:.56});
const sculptureMat=material(0x90927b,{roughness:.84});
const boxGeo=new THREE.BoxGeometry(1,1,1),sphereGeo=new THREE.SphereGeometry(1,12,8),coneGeo=new THREE.ConeGeometry(1,1,7);
function box(parent,x,y,z,w,h,d,mat=stoneMat){const m=new THREE.Mesh(boxGeo,mat);m.position.set(x,y,z);m.scale.set(w,h,d);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
function ball(parent,x,y,z,w,h,d,mat){const m=new THREE.Mesh(sphereGeo,mat);m.position.set(x,y,z);m.scale.set(w,h,d);parent.add(m);return m;}
const flameTex=texCanvas(64,128,(c,w,h)=>{let g=c.createRadialGradient(32,89,2,32,70,55);g.addColorStop(0,'#ffffdcff');g.addColorStop(.18,'#ffda68ef');g.addColorStop(.45,'#ff861aae');g.addColorStop(.73,'#ee450032');g.addColorStop(1,'#f6420000');c.fillStyle=g;c.fillRect(0,0,w,h);});
const glowTex=texCanvas(64,64,(c,w,h)=>{let g=c.createRadialGradient(32,32,1,32,32,31);g.addColorStop(0,'#ffe392bb');g.addColorStop(.2,'#ffbc4188');g.addColorStop(1,'#ff9f1500');c.fillStyle=g;c.fillRect(0,0,w,h);});
let resolveFire,rejectFire;
const fireReady=new Promise((resolve,reject)=>{resolveFire=resolve;rejectFire=reject;});
const fireTexture=new THREE.TextureLoader().load(ASSETS.fireAtlas,resolveFire,undefined,rejectFire);fireTexture.colorSpace=THREE.SRGBColorSpace;fireTexture.generateMipmaps=false;fireTexture.minFilter=THREE.LinearFilter;
const fireVertex='varying vec2 vUv; void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}';
const fireFragment=`varying vec2 vUv;uniform sampler2D uAtlas;uniform float uTime;uniform float uSeed;
vec4 flameFrame(float frame,vec2 uv){float col=mod(frame,4.);float row=floor(frame/4.);return texture2D(uAtlas,(vec2(col,3.-row)+uv)/4.);}
void main(){vec2 uv=vUv;uv.x+=sin(uv.y*9.-uTime*3.4+uSeed)*uv.y*.012;uv=clamp(uv,vec2(.014),vec2(.986));float t=uTime*13.+uSeed;float f=mod(floor(t),16.);vec4 a=flameFrame(f,uv),b=flameFrame(mod(f+1.,16.),uv);vec4 c=mix(a,b,smoothstep(.15,.85,fract(t)));float edge=smoothstep(0.,.045,vUv.y)*(1.-smoothstep(.93,1.,vUv.y));c.a*=edge*.94;if(c.a<.015)discard;gl_FragColor=vec4(c.rgb*1.6,c.a);
#include <tonemapping_fragment>
#include <colorspace_fragment>
}`;
const fireGeo=new THREE.PlaneGeometry(1,1);
function fire(parent,x,y,z,scale=1){const g=new THREE.Group();g.position.set(x,y,z);for(let i=0;i<2;i++){const mat=new THREE.ShaderMaterial({vertexShader:fireVertex,fragmentShader:fireFragment,uniforms:{uAtlas:{value:fireTexture},uTime:{value:0},uSeed:{value:rnd()*16}},transparent:true,depthWrite:false,side:THREE.DoubleSide});const sp=new THREE.Mesh(fireGeo,mat);sp.position.set((i-.5)*.10,.78,(i-.5)*.12);sp.scale.set(1.55,1.75+(i%2)*.22,1);sp.userData.phase=rnd()*7;g.add(sp);}g.scale.setScalar(scale);g.userData.fire=true;parent.add(g);return g;}
const sections=[];let sx=0,sz=0,ss=0,angle=0;for(let i=0;i<200;i++){let length=i===0?74:i===1?128:104+(i%3)*16;sections.push({s:ss,end:ss+length,x:sx,z:sz,angle,turn:i%2===0?'right':'left'});sx+=Math.sin(angle)*length;sz-=Math.cos(angle)*length;ss+=length;angle+=(i%2===0?1:-1)*Math.PI/2;}
function extendPath(s){if(sections[sections.length-1].end-s>220)return;for(let k=0;k<40;k++){const i=sections.length,length=104+(i%3)*16,sec={s:ss,end:ss+length,x:sx,z:sz,angle,turn:i%2===0?'right':'left'};sections.push(sec);sx+=Math.sin(angle)*length;sz-=Math.cos(angle)*length;ss+=length;angle+=(i%2===0?1:-1)*Math.PI/2;populateSection(sec,i);}}
function path(s){s=Math.max(0,s);extendPath(s);let p=sections.find(q=>s<q.end)||sections[sections.length-1];return{x:p.x+Math.sin(p.angle)*(s-p.s),z:p.z-Math.cos(p.angle)*(s-p.s),angle:p.angle,section:p};}
function place(g,s,lane=0,y=0){const p=path(s);g.position.set(p.x+Math.cos(p.angle)*lane,y,p.z+Math.sin(p.angle)*lane);g.rotation.y=-p.angle;return p;}
// Road modules keep a constant number of draw objects as the run advances.
function roadModule(){const g=new THREE.Group();box(g,0,-.35,0,6.3,.7,4.02);for(const x of [-3.23,3.23]){box(g,x,.15,0,.58,.9,4,darkMat);box(g,x,.68,-1.1,.73,.38,1.45);box(g,x,.56,1,.67,.18,2.5);box(g,x,-2.25,0,.57,3.9,2,darkMat);for(let j=0;j<3;j++)box(g,x-.1,.8+j*.09,-1+j*.4,.48,.07,.55,mossMat);}return g;}
const roadPool=Array.from({length:45},()=>{const g=roadModule();scene.add(g);return g;});
function templeModule(){const g=new THREE.Group();for(const x of [-4,4]){box(g,x,3.8,0,1.7,8,2,darkMat);for(let k=0;k<10;k++){box(g,x,k*.76+.25,0,1.92,.14,2.15);if(k%3===0)box(g,x,1+k*.6,-1.15,.7,.48,.17,blackMat);}box(g,x,.55,0,2.3,1.1,2.8);box(g,x,7.9,0,2.5,.6,2.8);box(g,x,3.1,1.38,.6,.26,.75,blackMat);fire(g,x,3.35,1.5,.9);}box(g,0,8.3,0,9.9,1.1,2.65,darkMat);box(g,0,9.05,0,8.9,.45,2.5);box(g,0,9.55,0,7.3,.6,2.2);box(g,0,10.1,0,5.3,.5,1.8);for(let i=0;i<9;i++)box(g,(i-4)*.8,8.3,1.37,.43,.7,.12,stoneMat);return g;}
const templePool=Array.from({length:5},()=>{let g=templeModule();scene.add(g);return g;});
const leafShape=new THREE.Shape();leafShape.moveTo(0,0);leafShape.quadraticCurveTo(.24,.18,0,.62);leafShape.quadraticCurveTo(-.24,.18,0,0);
const leafGeometry=new THREE.ShapeGeometry(leafShape,4),leafMat=material(0x5c7035,{side:THREE.DoubleSide,roughness:.92});
function vine(parent,points,r=.05){const curve=new THREE.CatmullRomCurve3(points.map(p=>new THREE.Vector3(...p)));const mesh=new THREE.Mesh(new THREE.TubeGeometry(curve,28,r*1.6,7,false),darkMat);parent.add(mesh);const foliage=new THREE.InstancedMesh(leafGeometry,leafMat,44),dummy=new THREE.Object3D();for(let i=0;i<44;i++){const p=curve.getPoint((i+.2)/44);dummy.position.copy(p);dummy.rotation.set(.2+rnd()*.8,rnd()*2,((i%2)?1:-1)*(.4+rnd()*.8));dummy.scale.setScalar(.6+rnd()*.65);dummy.updateMatrix();foliage.setMatrixAt(i,dummy.matrix);}foliage.receiveShadow=true;foliage.castShadow=true;parent.add(foliage);}

const leaves=texCanvas(256,256,(c)=>{for(let branch=0;branch<7;branch++){c.save();c.translate(128,253);c.rotate((branch-3)*.26);c.strokeStyle='#6b7746';c.lineWidth=1.3;c.beginPath();c.moveTo(0,0);c.quadraticCurveTo(4,-80,0,-214);c.stroke();for(let j=0;j<26;j++){let y=-12-j*7.5,l=33*Math.sin((j+3)/30*Math.PI);for(const side of [-1,1]){c.fillStyle=['#3c542d','#637446','#52633a','#7a8550'][j%4];c.beginPath();c.moveTo(0,y);c.quadraticCurveTo(side*l*.7,y-2,side*l,y-14);c.quadraticCurveTo(side*l*.45,y-11,0,y-3);c.fill();}}c.restore();}});
const fernTex=new THREE.TextureLoader().load(ASSETS.fern);fernTex.colorSpace=THREE.SRGBColorSpace;fernTex.anisotropy=4;
const fernMat=new THREE.MeshStandardMaterial({map:fernTex,alphaTest:.42,side:THREE.DoubleSide,color:0xb7be95,roughness:1,envMapIntensity:.7,transparent:false});
const fernGeo=new THREE.PlaneGeometry(1,1,3,3);fernGeo.translate(0,.5,0);
function greenery(){const g=new THREE.Group();for(let side of [-1,1]){vine(g,[[side*4,11,-2],[side*3,8,1],[side*3.8,5,0],[side*3.1,1,0]],.032);vine(g,[[side*5,9,-3],[side*2,7,-1],[side*.3,8,1]],.027);for(let j=0;j<7;j++){const cluster=new THREE.Group();cluster.position.set(side*(j<4?3.05+rnd()*1.4:3.2+rnd()*.35),j<4?.85+rnd()*.3:2+rnd()*4,(rnd()-.5)*9);cluster.scale.setScalar(1+rnd()*.8);cluster.rotation.y=rnd()*Math.PI;for(let k=0;k<2;k++){const m=new THREE.Mesh(fernGeo,fernMat);m.rotation.y=k*Math.PI/2;m.receiveShadow=true;cluster.add(m);}g.add(cluster);}}return g;}
const greenPool=Array.from({length:9},()=>{let g=greenery();scene.add(g);return g;});
const zoneDetails=Array.from({length:8},()=>{const root=new THREE.Group(),vines=new THREE.Group(),water=new THREE.Group(),fireZone=new THREE.Group();
 for(const side of [-1,1]){box(vines,side*3.4,2.25,0,.62,4.5,.72,darkMat);box(vines,side*3.4,4.55,0,1.1,.3,1.1);vine(vines,[[side*3.6,5.7,0],[side*2.9,4,0],[side*3.3,1,0]],.027);
 box(water,side*3.4,1.1,0,.78,2.2,.8,darkMat);box(water,side*3.4,2.25,0,1.1,.2,1.1);
 box(fireZone,side*3.3,1.15,0,.9,2.3,.9,darkMat);fire(fireZone,side*3.3,2.35,0,.95);}
 root.add(vines,water,fireZone);root.userData.variants=[vines,water,fireZone];scene.add(root);return root;});
const mistTex=texCanvas(128,128,c=>{const g=c.createRadialGradient(64,64,4,64,64,62);g.addColorStop(0,'#d8e9dacf');g.addColorStop(.4,'#c5ddd469');g.addColorStop(1,'#c5ddd400');c.fillStyle=g;c.fillRect(0,0,128,128);});
const mistPool=Array.from({length:10},(_,i)=>{const m=new THREE.Sprite(new THREE.SpriteMaterial({map:mistTex,transparent:true,opacity:.2,depthWrite:false,fog:false}));m.scale.set(25,9,1);scene.add(m);return m;});
function updateAtmosphere(){zoneDetails.forEach((g,i)=>{const d=(Math.floor(state.s/18)-1+i)*18;g.visible=d>=205&&d-state.s<90;place(g,d);const z=RELIC_CONTENT.zoneAt(d);g.userData.variants.forEach((c,j)=>c.visible=j===z);});mistPool.forEach((m,i)=>{const d=(Math.floor(state.s/16)-2+i)*16;const p=path(Math.max(0,d));const side=i%2?1:-1;m.position.set(p.x+Math.cos(p.angle)*side*(9+Math.sin(renderTime*.12+i)*3),-4-(i%3)*3,p.z+Math.sin(p.angle)*side*9);m.material.opacity=RELIC_CONTENT.zoneAt(state.s)===1?.26:.15;});}
function serpent(){const g=new THREE.Group();for(let side of [-1,1]){box(g,side*3.25,1.1,0,1,1.8,1.2);const pts=[[side*3.25,1.5,0],[side*3.6,2.1,0],[side*3.1,2.8,0],[side*3.4,3.5,0],[side*2.9,3.7,.2]];let curve=new THREE.CatmullRomCurve3(pts.map(p=>new THREE.Vector3(...p)));g.add(new THREE.Mesh(new THREE.TubeGeometry(curve,25,.26,9,false),darkMat));ball(g,side*2.85,3.65,.27,.42,.28,.46,stoneMat);ball(g,side*2.65,3.72,.64,.075,.06,.04,goldMat);for(let j=0;j<17;j++){let p=curve.getPoint(j/17);ball(g,p.x,p.y,p.z+.22,.27,.09,.06,stoneMat);}}return g;}
const snakes=[serpent(),serpent()];snakes.forEach(g=>scene.add(g));
const shadowTex=texCanvas(128,128,c=>{let g=c.createRadialGradient(64,64,3,64,64,60);g.addColorStop(0,'#051108b0');g.addColorStop(1,'#05110800');c.fillStyle=g;c.fillRect(0,0,128,128);});const shadow=new THREE.Mesh(new THREE.PlaneGeometry(1.7,1.6),new THREE.MeshBasicMaterial({map:shadowTex,transparent:true,depthWrite:false}));shadow.rotation.x=-Math.PI/2;scene.add(shadow);
const runner=new THREE.Group();scene.add(runner);let runner3d=null;const runnerReady=createRelicRunner(ASSETS.runner).then(r=>{runner3d=r;r.model.scale.setScalar(1.78);runner.add(r.model);});
let best=0;try{best=Number(localStorage.getItem('relic-run-best-v1'))||0;}catch{}$('#best').textContent=best;
const initialState=()=>({mode:'cover',s:0,time:0,speed:10,lane:0,x:0,y:0,vy:0,slide:0,stumble:0,pressure:.25,coins:0,score:0,turnInput:null,turnUntil:0,nextTurn:0,demo:false,demoEnd:false,deathReason:'',events:[],lastCoin:-1,passed:0,nearMisses:0,jumps:0,slides:0,turns:0,dodges:0,invuln:0,relics:0,practice:false});let state=initialState();let builtRoad=-999,renderTime=0,camYaw=0,flash=0,hintExpiry=0,activeHint='',soundOn=true,audio=null,lastStep=0;
const obstacles=[];function addObstacle(type,s,lanes){obstacles.push({type,s,lanes,hit:false,done:false,object:null});}
addObstacle('fire',40);addObstacle('beam',103);addObstacle('crumble',135);addObstacle('spikes',163,[-1,0]);

const coins=[];for(let i=0;i<2;i++){const sec=sections[i];for(let j=0;j<6;j++){coins.push({s:sec.s+12+j*2.8,lane:0,taken:false,object:null});if(i===1||i>1)coins.push({s:sec.end-26+j*2.5,lane:i%2?1:0,taken:false,object:null});}}
let runSeed=9182;const relics=[];
function populateSection(sec,i){const c=RELIC_CONTENT.build(sec,i,runSeed);for(const o of c.objects)obstacles.push({...o,hit:false,done:false,object:null});coins.push(...c.coins);relics.push(...c.relics);}
function refreshContent(demo){runSeed=demo?9182:Math.floor(Math.random()*2147483647);for(const list of [obstacles,coins,relics])for(const o of list)if(o.s>=202&&o.object)removeTransient(o.object);obstacles.splice(4);coins.splice(18);relics.length=0;for(let i=2;i<sections.length;i++)populateSection(sections[i],i);for(const g of relicRoadCache.values())g.dispose();relicRoadCache.clear();}
for(let i=2;i<sections.length;i++)populateSection(sections[i],i);
const coinGeo=new THREE.TorusGeometry(.27,.048,5,4);const coinCore=new THREE.OctahedronGeometry(.09,0);
function makeCoin(){const g=new THREE.Group();g.add(new THREE.Mesh(coinGeo,goldMat));g.add(new THREE.Mesh(coinCore,goldMat));const gl=new THREE.Sprite(new THREE.SpriteMaterial({map:glowTex,transparent:true,depthWrite:false,blending:THREE.AdditiveBlending}));gl.scale.set(1,1,1);g.add(gl);return g;}
function removeTransient(object){scene.remove(object);object.traverse(o=>{if(o.material&&(o.material.isShaderMaterial||o.material.isSpriteMaterial))o.material.dispose();});}
function makeObstacle(o){const g=new THREE.Group();if(o.type==='rubble'){for(const lane of o.lanes){box(g,lane*1.85,.4,0,1.7,.8,1.5,darkMat);for(let k=0;k<3;k++){let b=box(g,lane*1.85+(k-1)*.42,.8+k%2*.15,0,.7,.45,.75,stoneMat);b.rotation.z=(k-1)*.19;}}}else if(o.type==='sweep'){for(const side of [-1,1])box(g,side*3.15,3.2,0,.5,6.4,.6,darkMat);box(g,0,6.2,0,6.8,.4,.6);const arm=new THREE.Group();arm.position.y=5.6;const rope=new THREE.Mesh(new THREE.CylinderGeometry(.045,.045,3.8,6),blackMat);rope.position.y=-1.9;arm.add(rope);const boulder=new THREE.Mesh(new THREE.IcosahedronGeometry(.78,2),darkMat);boulder.position.y=-4;arm.add(boulder);g.add(arm);g.userData.swing=arm;}else if(o.type==='jets'){for(const lane of o.lanes){box(g,lane*1.85,.08,0,1.65,.15,1.6,blackMat);fire(g,lane*1.85,.05,0,1.35);}for(const side of [-1,1])box(g,side*3.1,.65,0,.4,1.3,1.2,darkMat);}else if(o.type==='fire'){box(g,0,-1.3,0,6,.06,2.5,blackMat);for(let k=-3;k<=3;k++){for(let j=0;j<2;j++){const spike=new THREE.Mesh(coneGeo,spikeMat);spike.position.set(k*.83,-.25,j*1.1-.65);spike.scale.set(.17,.85,.17);g.add(spike);}}for(let k=-5;k<=5;k++)fire(g,k*.57,.13,-.5,1.15+((k+6)%3)*.1);box(g,0,.05,1.4,6,.17,.25,darkMat);box(g,0,.05,-1.4,6,.17,.25,darkMat);}else if(o.type==='beam'){box(g,0,2.55,0,6.8,1.5,1.9,darkMat);for(let side of [-1,1]){box(g,side*3,.6,0,.65,1.7,2);box(g,side*3,3.4,0,1,.3,2.3);}for(let k=-3;k<=3;k++)box(g,k*.8,2.2,1,.4,.8,.12,stoneMat);}else if(o.type==='crumble'){box(g,0,.08,0,5.8,.22,2.9,darkMat);for(let i=0;i<6;i++){let m=box(g,(i%3-1)*1.85,.21,Math.floor(i/3)*1.3-.7,1.78,.15,1.2,stoneMat);m.rotation.y=(rnd()-.5)*.07;}}else if(o.type==='spikes'){for(let lane of o.lanes){if(lane===-1&&o.s===163){for(let k=0;k<3;k++){const r=box(g,-1.85+(k-1)*.55,-.8-k*.45,.4-k*.6,.5,.2,.6,darkMat);r.rotation.z=.6;}continue;}box(g,lane*1.85,.08,0,1.77,.15,2.8,blackMat);for(let a=0;a<3;a++)for(let b=0;b<4;b++){const m=new THREE.Mesh(coneGeo,spikeMat);m.position.set(lane*1.85+(a-1)*.48,.7,(b-1.5)*.64);m.scale.set(.19,1.35,.19);g.add(m);}}}place(g,o.s);scene.add(g);return g;}
function updateWorld(){let n=Math.floor(state.s/4);if(n!==builtRoad){builtRoad=n;roadPool.forEach((g,i)=>{const s=(n-5+i)*4+2;g.visible=s>=0;place(g,s);if(g.userData.blenderRoad)cutRelicRoad(g,s,obstacles);});templePool.forEach((g,i)=>{let s=(Math.floor(state.s/48)-1+i)*48+48;g.visible=s>5&&s-state.s<100&&!sections.some(q=>Math.abs(q.end-s)<9);place(g,s);});greenPool.forEach((g,i)=>{const at=(Math.floor(state.s/20)-1+i)*20;g.visible=!sections.some(q=>Math.abs(q.end-at)<7);place(g,at);});snakes.forEach((g,i)=>place(g,Math.floor(state.s/88)*88+19+i*44));}
 for(const o of obstacles){let d=o.s-state.s;if(d>-10&&d<135){if(!o.object)o.object=makeObstacle(o);o.object.visible=true;if(o.type==='sweep')o.object.userData.swing.rotation.z=Math.asin(RELIC_CONTENT.sweepX(o,state.time)/4);if(o.type==='jets')for(const child of o.object.children)if(child.userData.fire){const active=RELIC_CONTENT.jetActive(o,state.time);child.visible=active||d>1&&d<14;child.scale.y=active?1.35:.2;}if(o.type==='crumble'){let f=clamp((state.time-(o.triggerTime??state.time))/.24,0,1);o.object.position.y=o.done?-.48*f:0;o.object.rotation.z=o.done?.055*f:0;}}else if(o.object){removeTransient(o.object);o.object=null;}}
 for(const c of coins){let d=c.s-state.s;if(d>-4&&d<95&&!c.taken){if(!c.object){c.object=makeCoin();scene.add(c.object);}place(c.object,c.s,c.lane*1.85,(c.height||1.35)+Math.sin(renderTime*3+c.s)*.05);c.object.rotation.y+=Math.sin(renderTime*2)*.23;}else if(c.object){removeTransient(c.object);c.object=null;}}
}
function updateRelics(){for(const r of relics){const d=r.s-state.s;if(d>-4&&d<95&&!r.taken){if(!r.object){const g=new THREE.Group();const body=new THREE.Mesh(new THREE.IcosahedronGeometry(.25,1),goldMat);body.scale.set(1,1.55,.7);g.add(body);const ring=new THREE.Mesh(new THREE.TorusGeometry(.39,.025,6,24),goldMat);g.add(ring);r.object=g;scene.add(g);}place(r.object,r.s,r.lane*1.85,r.height+Math.sin(renderTime*2)*.06);r.object.rotation.y=renderTime*1.4;}else if(r.object){removeTransient(r.object);r.object=null;}}}

function setHint(msg,duration=1.4){activeHint=msg;hintExpiry=state.time+duration;$('#hint').textContent=msg;$('#hint').style.opacity=1;}
function audioInit(){if(!soundOn)return;try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();audio.resume();}catch{}}
function tone(freq,duration,vol=.04,type='sine',end=freq){if(!audio||!soundOn)return;const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(freq,audio.currentTime);o.frequency.exponentialRampToValueAtTime(Math.max(end,10),audio.currentTime+duration);g.gain.setValueAtTime(vol,audio.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+duration);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+duration);}
function rumble(duration=.3,vol=.07){if(!audio||!soundOn)return;const buffer=audio.createBuffer(1,audio.sampleRate*duration,audio.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=(Math.random()*2-1)*(1-i/data.length);const s=audio.createBufferSource(),f=audio.createBiquadFilter(),g=audio.createGain();f.type='lowpass';f.frequency.value=400;g.gain.value=vol;s.buffer=buffer;s.connect(f);f.connect(g);g.connect(audio.destination);s.start();}
function log(type,detail=''){state.events.push({type,time:+state.time.toFixed(3),s:+state.s.toFixed(2),detail});if(state.events.length>100)state.events.shift();}
function act(action){if(state.mode!=='playing')return;const turn=sections[state.nextTurn],td=turn.end-state.s;if(action==='left'||action==='right'){if(td<16&&td>-.5){state.turnInput=action;state.turnUntil=turn.end+1;setHint(action==='right'?'右转已就绪 ↱':'↰ 左转已就绪',.8);log('turn-input',action);return;}state.lane=clamp(state.lane+(action==='right'?1:-1),-1,1);state.dodges++;log('lane',state.lane);tone(150,.08,.012,'sine',90);}else if(action==='jump'&&state.y<=.01&&state.slide<=0){state.vy=9.2;state.jumps++;log('jump');tone(180,.18,.02,'sine',420);}else if(action==='slide'&&state.y<.2&&state.slide<=0){state.slide=.95;state.slides++;log('slide');rumble(.25,.04);}}
function hurt(reason,fatal=false){if(state.invuln>0)return;state.pressure+=.52;state.stumble=.7;state.invuln=1.35;flash=.38;state.nearMisses++;log('hit',reason);rumble(.55,.15);setHint('追兵逼近 · 稳住脚步',1.5);if(fatal||state.pressure>=1.05)die(reason);}
function die(reason){state.mode='dead';state.deathReason=reason;log('death',reason);saveBest();showOverlay('逃亡结束','守护者追上了你。',reason+'<br>记住机关的位置，再跑远一点。',false);}
let bestScore=0,bestRelics=0;try{bestScore=Number(localStorage.getItem('relic-run-score-v1'))||0;bestRelics=Number(localStorage.getItem('relic-run-relics-v1'))||0;}catch{}
function showRecords(){$('#bestScore').textContent=`最高分 ${bestScore.toLocaleString()} · 单次遗物 ${bestRelics}`;}showRecords();
function saveBest(){if(state.practice||state.demo)return;bestScore=Math.max(bestScore,state.score);bestRelics=Math.max(bestRelics,state.relics||0);showRecords();try{localStorage.setItem('relic-run-score-v1',String(bestScore));localStorage.setItem('relic-run-relics-v1',String(bestRelics));}catch{}best=Math.max(best,Math.floor(state.s));$('#best').textContent=best;try{localStorage.setItem('relic-run-best-v1',String(best));}catch{}}
function showOverlay(eyebrow,title,text,resume){$('#overlay').hidden=false;$('#overline').textContent=eyebrow;$('#overTitle').textContent=title;$('#overText').innerHTML=text;$('#stats').innerHTML=`<div>${Math.floor(state.s)}<small>米 / 距离</small></div><div>${state.coins}<small>符文金币</small></div><div>${state.relics||0}<small>古代遗物</small></div>`;$('#overText').innerHTML+=`<br><span class=run-summary>${state.score.toLocaleString()} 分 · ${state.passed} 道机关 · ${RELIC_CONTENT.zones[RELIC_CONTENT.zoneAt(state.s)]||'初入遗迹'}${state.practice?' · 区域练习':''}<br>正式逃亡最高分 ${bestScore.toLocaleString()}</span>`;updatePractice();$('#resume').hidden=!resume;$('#restart').className=resume?'textbutton':'primary';$('#restart').textContent=resume?'重新开始':'再次逃亡 →';}
function pause(){if(state.mode==='playing'){state.mode='paused';showOverlay('片刻喘息','追逐，暂时停下。','准备好后，继续前进。',true);}else if(state.mode==='paused'){state.mode='playing';$('#overlay').hidden=true;audioInit();}}
function start(demo=false){obstacles.forEach(o=>{o.hit=false;o.done=false;o.triggerTime=null;});coins.forEach(c=>{c.taken=false;});state=initialState();state.mode='playing';state.demo=demo;refreshContent(demo);environmentDetail?.invalidate();const entry=demo?0:Number($('#practiceSelect')?.value||0);if(entry&&best>=entry){state.s=entry;state.nextTurn=sections.findIndex(sec=>sec.s===entry);state.practice=true;}camYaw=path(state.s).angle;runner3d?.reset();builtRoad=-999;flash=0;lastStep=0;$('#cover').hidden=true;$('#overlay').hidden=true;$('#gamebar').hidden=true;$('#touch').hidden=true;$('#modeLabel').textContent=demo?'20 秒演示 · 自动操作':'向前奔跑 · 别回头';$('#hint').textContent='';$('#turnCue').textContent='';audioInit();setHint(demo?'演示中 · 跳跃 → 转弯 → 滑行':'↑ 跳跃　↓ 滑行　← → 闪避',2.4);stage.focus();updateWorld();}
function autoPilot(){const turn=sections[state.nextTurn];if(turn.end-state.s<9&&!state.turnInput)act(turn.turn);for(const o of obstacles){let d=o.s-state.s;if(o.done||d<0||d>8)continue;if(o.type==='fire'&&d<4.8&&state.y<.01)act('jump');if(o.type==='beam'&&d<4.3&&state.slide<=0)act('slide');if(o.type==='rubble'&&d<4.8&&o.lanes.includes(state.lane)&&state.y<.01)act('jump');if((o.type==='jets'||o.type==='sweep')&&d<7){const arrive=state.time+Math.max(0,d-1)/state.speed;let safe=o.type==='jets'?[-1,0,1].filter(l=>!o.lanes.includes(l)):[-1,0,1].filter(l=>Math.abs(l*1.85-RELIC_CONTENT.sweepX(o,arrive))>1.15);if(safe.length&&!safe.includes(state.lane)){safe.sort((a,b)=>Math.abs(a-state.lane)-Math.abs(b-state.lane));act(safe[0]>state.lane?'right':'left');}}if(o.type==='spikes'&&d<7){let safe=[-1,0,1].find(l=>!o.lanes.includes(l));if(state.lane!==safe)act(safe>state.lane?'right':'left');}}}
function step(dt){if(state.mode!=='playing')return;if(runner3d)runner3d.update(state,dt);state.monsterPulse=Math.max(0,(state.monsterPulse||0)-dt);state.time+=dt;state.invuln=Math.max(0,state.invuln-dt);state.slide=Math.max(0,state.slide-dt);state.stumble=Math.max(0,state.stumble-dt);state.pressure=Math.max(.06,state.pressure-dt*.032);state.speed=10+Math.min(6,Math.max(0,state.s-220)/650);if(state.demo)autoPilot();const oldS=state.s;state.s+=state.speed*dt*(state.stumble>0?.78:1);state.x=lerp(state.x,state.lane*1.85,1-Math.exp(-dt*14));if(state.y>0||state.vy>0){state.vy-=22*dt;state.y=Math.max(0,state.y+state.vy*dt);if(state.y===0&&state.vy<0){state.vy=0;rumble(.14,.035);log('land');state.monsterPulse=.6;}}
 const turn=sections[state.nextTurn];if(state.s>=turn.end){if(state.turnInput===turn.turn){state.turns++;state.nextTurn++;state.turnInput=null;state.lane=0;state.pressure=Math.max(.06,state.pressure-.16);log('turn',turn.turn);rumble(.12,.03);setHint('继续奔跑',.65);}else{state.s=turn.end-.03;die('在拐角前按'+(turn.turn==='right'?' → 右转':' ← 左转')+'。');return;}}
 for(const o of obstacles){if(o.done||o.s>state.s+1.15||o.s<oldS-3)continue;o.done=true;o.triggerTime=state.time;let success=true;if(o.type==='rubble'&&o.lanes.some(l=>Math.abs(state.x-l*1.85)<.85)&&state.y<1.05){success=false;hurt('石堆挡路：跳过去，或换到另一条路线。');}else if(o.type==='jets'&&RELIC_CONTENT.jetActive(o,state.time)&&o.lanes.some(l=>Math.abs(state.x-l*1.85)<.82)){success=false;hurt('喷火石板正在燃烧，旁边留有安全路线。');}else if(o.type==='sweep'&&Math.abs(state.x-RELIC_CONTENT.sweepX(o,state.time))<1.03&&state.y+(state.slide>0?1.15:3.1)>5.6-Math.sqrt(16-RELIC_CONTENT.sweepX(o,state.time)**2)-.78){success=false;hurt('巨石摆锤逼近，需要观察摆动方向再换道。');}else if(o.type==='fire'&&state.y<.9){success=false;hurt('烈焰断桥需要提前跳跃。',true);}else if(o.type==='beam'&&state.slide<=0){success=false;hurt('低石梁需要下滑通过。');}else if(o.type==='spikes'&&o.lanes.some(l=>Math.abs(state.x-l*1.85)<.82)&&(o.s===163||state.y<1.25)){success=false;hurt(o.s===163&&state.x<-.92?'左侧石板已经坍塌，只有右侧安全。':'尖刺弹出，请及时移到安全路线或跳过。',o.s===163&&state.x<-.92);}else if(o.type==='crumble'&&state.y<.45){state.stumble=.62;state.pressure=Math.min(.82,state.pressure+.32);state.nearMisses++;log('near-miss','crumbling stone');rumble(.4,.1);setHint('石板松动 · 稳住！',1.1);}if(success&&o.type!=='crumble'){state.passed++;state.pressure=Math.max(.06,state.pressure-.1);log('clear',o.type);}}
 for(const c of coins){if(!c.taken&&Math.abs(c.s-state.s)<.75&&Math.abs(state.x-c.lane*1.85)<.7&&(c.s<202?state.y<1.6:Math.abs(state.y+1.35-(c.height||1.35))<.9)){c.taken=true;state.coins++;tone(860+(state.coins%5)*90,.1,.022,'sine',1450);log('coin');}}
 for(const r of relics){if(!r.taken&&Math.abs(r.s-state.s)<.8&&Math.abs(state.x-r.lane*1.85)<.65&&Math.abs(state.y+1.35-r.height)<.85){r.taken=true;state.relics++;log('relic',r.id);tone(620,.22,.024,'sine',1600);}}if(!state.practice&&[202,562,922].some(m=>oldS<m&&state.s>=m)){saveBest();updatePractice();}state.score=Math.floor((state.s-(state.practice?Number($('#practiceSelect').value):0))*12)+state.coins*50+state.relics*750;const foot=Math.floor(state.time*3.8);if(foot!==lastStep&&state.y===0&&state.slide<=0){rumble(.055,.024);lastStep=foot;}
 if(state.demo&&state.time>=20){state.mode='demo-done';state.demoEnd=true;showOverlay('20 秒 · 连续逃亡','下一段路，交给你。','现在亲自控制跳跃、滑行、转弯和闪避。',false);$('#restart').textContent='亲自开始逃亡 →';}
}
function render(dt){renderTime+=dt;updateWorld();environmentDetail?.update(state.s);routeReadability?.update(state,sections);updateRelics();updateAtmosphere();const p=path(state.s),running=state.mode==='playing';runner.position.set(p.x+Math.cos(p.angle)*state.x,state.y+.025,p.z+Math.sin(p.angle)*state.x);runner.rotation.set(0,Math.PI-p.angle,-(state.lane*1.85-state.x)*.065);shadow.position.set(runner.position.x,.018,runner.position.z);shadow.material.opacity=1-state.y*.2;
 let da=p.angle-camYaw;camYaw+=da*(1-Math.exp(-dt*15));runner.rotation.y=Math.PI-camYaw;let fx=Math.sin(camYaw),fz=-Math.cos(camYaw),rx=Math.cos(camYaw),rz=Math.sin(camYaw),cy=6.55+state.y*.15-(state.slide>0?.25:0);camera.position.set(p.x-fx*10.1+rx*state.x*.27,cy,p.z-fz*10.1+rz*state.x*.27);camera.lookAt(p.x+fx*5+rx*state.x*.16,1.2,p.z+fz*5+rz*state.x*.16);
 scene.traverse(o=>{if(o.userData.fire){o.children.forEach((f,i)=>{const t=renderTime*8+f.userData.phase;f.material.uniforms.uTime.value=renderTime;f.scale.y=1.75+(i%2)*.22+Math.sin(t*.7)*.06;f.position.x=(i-.5)*.10+Math.sin(t*.4+i)*.025;});}});
 $('#backdrop').style.backgroundPosition=`${50+Math.sin(camYaw)*20+Math.sin(state.s*.001)*3}% 50%`;let presence=state.time<2.5?.85:state.stumble>0?.98:state.monsterPulse>0?.65:state.time>18&&state.time<21?.7:state.pressure+.03*Math.sin(state.time*2);if(state.mode==='cover')presence=.7;$('#pursuer').style.transform=`translateY(${(1-presence)*47+Math.sin(state.time*9)*1.2}%)`;$('#pursuer').style.opacity=clamp(presence*1.7,.07,1);
 $('#score').textContent=String(state.score).padStart(6,'0');$('#distance').innerHTML=Math.floor(state.s)+'<span>m</span>';$('#coins').textContent='×'+state.coins;
 if(state.time>hintExpiry)$('#hint').style.opacity=0;const turn=sections[state.nextTurn],d=turn.end-state.s;$('#turnCue').textContent=running&&d<15?(turn.turn==='right'?'↱':'↰'):'';if(running&&!state.demo&&state.time>hintExpiry){const o=obstacles.find(o=>!o.done&&o.s-state.s>0&&o.s-state.s<17);if(o&&o.type!=='crumble'){$('#hint').textContent=o.type==='fire'?'↑  跳过烈焰':o.type==='beam'?'↓  滑过石梁':o.lanes.includes(-1)?'→  右侧安全':'←  左侧安全';$('#hint').style.opacity=.9;}}
 const hot=obstacles.find(o=>(o.type==='fire'||o.type==='jets'&&RELIC_CONTENT.jetActive(o,state.time))&&Math.abs(o.s-state.s)<24);if(hot){const h=path(hot.s);fireBounce.position.set(h.x,1.5,h.z);fireBounce.intensity=22;}else fireBounce.intensity=0;sun.position.set(p.x-14,28,p.z+8);sun.target.position.set(p.x,0,p.z-10);flash=Math.max(0,flash-dt);$('#flash').style.opacity=flash;renderer.render(scene,camera);
}
function resize(){const r=stage.getBoundingClientRect();renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix();}new ResizeObserver(resize).observe(stage);
function blenderModel(data){const group=new THREE.Group();for(const batch of data.batches){const positions=[],normals=[],uvs=[];for(const row of batch.vertices){positions.push(...row.slice(0,3));normals.push(...row.slice(3,6));uvs.push(...row.slice(6,8).map(v=>data.name==='road-module'?v*.532:v));}const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));geo.setAttribute('normal',new THREE.Float32BufferAttribute(normals,3));geo.setAttribute('uv',new THREE.Float32BufferAttribute(uvs,2));geo.computeBoundingSphere();const mesh=new THREE.Mesh(geo,(data.name==='serpent-pair'?[sculptureMat,mossMat,blackMat]:[stoneMat,mossMat,blackMat])[batch.material]);mesh.castShadow=true;mesh.receiveShadow=true;group.add(mesh);}return group;}
const modelReady=window.RELIC_MODELS?Promise.resolve(window.RELIC_MODELS):Promise.all(['temple-gate','serpent-pair','road-module'].map(name=>fetch('assets/'+name+'.json').then(r=>{if(!r.ok)throw Error('Missing '+name);return r.json();})));
// A textured facade mesh follows the observed stone silhouette, including the
// genuinely open doorway. No rectangle of background pixels enters the scene.
const facadeReady=imageLoad(ASSETS.facade).then(img=>{
 const outline=[[.04,.015],[.04,.065],[.08,.135],[.09,.69],[.126,.70],[.135,.993],[.868,.993],[.89,.71],[.917,.69],[.93,.14],[.961,.068],[.962,.015],[.613,.015],[.612,.478],[.39,.478],[.389,.015]];
 const mapX=u=>u<.39?-3.3+(u-.39)*8:u>.612?3.3+(u-.612)*8:(u-.501)*29.73;
 const shape=new THREE.Shape();outline.forEach(([u,v],i)=>{i?shape.lineTo(mapX(u),v*18):shape.moveTo(mapX(u),v*18)});shape.closePath();const geo=new THREE.ShapeGeometry(shape);const pos=geo.attributes.position,uv=[];for(let i=0;i<pos.count;i++){const x=pos.getX(i);uv.push(x< -3.3?.39+(x+3.3)/8:x>3.3?.612+(x-3.3)/8:.501+x/29.73,pos.getY(i)/18);}geo.setAttribute('uv',new THREE.Float32BufferAttribute(uv,2));
 const texture=new THREE.Texture(img);texture.colorSpace=THREE.SRGBColorSpace;texture.anisotropy=8;texture.needsUpdate=true;
 const mesh=new THREE.Mesh(geo,new THREE.MeshBasicMaterial({map:texture,color:0xd3cfc1,side:THREE.DoubleSide,toneMapped:false}));mesh.position.z=1.95;mesh.castShadow=true;return mesh;
});
Promise.all([modelReady,facadeReady]).then(([,facade])=>{templePool.forEach(g=>{g.add(facade.clone());box(g,0,-.62,0,14.7,1.2,3.6,darkMat);for(const x of [-5,5])box(g,x,-5,0,2.8,10,3.5,darkMat);for(const child of g.children)if(child.userData.fire)child.position.z=2.8;for(const x of [-4,4]){box(g,x,3.46,2.43,.8,.24,.8,blackMat);ball(g,x,3.57,2.58,.4,.15,.4,blackMat);}});});
modelReady.then(([gateData,snakeData,roadData])=>{const gate=blenderModel(gateData),snake=blenderModel(snakeData),road=blenderModel(roadData);roadPool.forEach((old,i)=>{scene.remove(old);roadPool[i]=road.clone();roadPool[i].userData.blenderRoad=true;scene.add(roadPool[i]);});templePool.forEach((old,i)=>{scene.remove(old);const g=gate.clone();for(const x of [-4,4])fire(g,x,3.72,1.62,.9);templePool[i]=g;scene.add(g);});snakes.forEach((old,i)=>{scene.remove(old);snakes[i]=snake.clone();scene.add(snakes[i]);});builtRoad=-999;}).catch(e=>console.error('Model loading failed',e));
function updatePractice(){for(const option of $('#practiceSelect').options)option.disabled=Number(option.value)>best;}updatePractice();
$('#menu').onclick=()=>{saveBest();state=initialState();runner3d?.reset();camYaw=0;builtRoad=-999;$('#overlay').hidden=true;$('#cover').hidden=false;$('#practiceSelect').value='0';updatePractice();$('#practiceSelect').focus();};
$('#start').onclick=()=>start(false);$('#demo').onclick=()=>start(true);$('#restart').onclick=()=>start(false);$('#resume').onclick=pause;$('#pause').onclick=pause;$('#sound').onclick=()=>{soundOn=!soundOn;$('#sound').textContent=soundOn?'♪':'♩';$('#sound').style.opacity=soundOn?1:.4;if(soundOn)audioInit();};
document.addEventListener('keydown',e=>{if(e.target.closest('select,input,textarea'))return;const map={ArrowUp:'jump',KeyW:'jump',Space:'jump',ArrowDown:'slide',KeyS:'slide',ArrowLeft:'left',KeyA:'left',ArrowRight:'right',KeyD:'right'};if(map[e.code]){e.preventDefault();if(e.repeat)return;if(state.mode==='cover'){if(e.code==='Space')start(false);}else if(!state.demo)act(map[e.code]);}if(e.code==='KeyP'||e.code==='Escape'){e.preventDefault();pause();}if(e.code==='KeyM')$('#sound').click();if(e.code==='Enter'&&(state.mode==='dead'||state.mode==='demo-done'))start(false);});
let pointer=null;stage.addEventListener('pointerdown',e=>{if(e.target.closest('button,select,label'))return;pointer={x:e.clientX,y:e.clientY};});stage.addEventListener('pointerup',e=>{if(!pointer||state.demo)return;const dx=e.clientX-pointer.x,dy=e.clientY-pointer.y;pointer=null;if(Math.max(Math.abs(dx),Math.abs(dy))<12){pause();return;}if(Math.max(Math.abs(dx),Math.abs(dy))>24)act(Math.abs(dx)>Math.abs(dy)?dx>0?'right':'left':dy<0?'jump':'slide');});stage.addEventListener('pointercancel',()=>pointer=null);document.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('pointerdown',e=>{e.preventDefault();if(!state.demo)act(b.dataset.action);}));document.addEventListener('visibilitychange',()=>{if(document.hidden&&state.mode==='playing')pause();});
let last=performance.now(),accumulator=0,manual=false;function loop(now){const dt=Math.min((now-last)/1000,.05);last=now;if(!manual){accumulator+=dt;while(accumulator>=1/120){step(1/120);accumulator-=1/120;}render(dt);}requestAnimationFrame(loop);}
window.render_game_to_text=()=>JSON.stringify({mode:state.mode,distance:+state.s.toFixed(2),time:+state.time.toFixed(2),lane:state.lane,x:+state.x.toFixed(2),height:+state.y.toFixed(2),slide:+state.slide.toFixed(2),pressure:+state.pressure.toFixed(2),score:state.score,coins:state.coins,turns:state.turns,passed:state.passed,relics:state.relics,zone:RELIC_CONTENT.zones[RELIC_CONTENT.zoneAt(state.s)]||'初入遗迹',seed:runSeed,practice:state.practice,next:obstacles.filter(o=>!o.done&&o.s>state.s).slice(0,2).map(o=>({type:o.type,distance:+(o.s-state.s).toFixed(1)})),nextTurn:{direction:sections[state.nextTurn].turn,distance:+(sections[state.nextTurn].end-state.s).toFixed(1)},events:state.events.slice(-10)});
window.advanceTime=ms=>{manual=true;for(let i=0;i<Math.round(ms/(1000/120));i++)step(1/120);render(.5);return window.render_game_to_text();};window.RELIC_TEST={start,act,pause,character:()=>runner3d?.info,getState:()=>state,setManual:v=>manual=v,render:()=>render(1/60)};
const pbrReady=Promise.all([new THREE.TextureLoader().loadAsync(ASSETS.stoneDiffuse),new THREE.TextureLoader().loadAsync(ASSETS.stoneNormal),new THREE.TextureLoader().loadAsync(ASSETS.stoneARM),new RelicRGBELoader().loadAsync(ASSETS.forestLight)]).then(([diffuse,normal,arm,hdr])=>{
 for(const t of [diffuse,normal,arm]){t.wrapS=t.wrapT=THREE.RepeatWrapping;t.repeat.set(.72,.72);t.anisotropy=8;}
 diffuse.colorSpace=THREE.SRGBColorSpace;
 for(const m of [stoneMat,darkMat,mossMat,sculptureMat]){m.map=diffuse;m.bumpMap=null;m.normalMap=normal;m.normalScale.set(.75,.75);m.roughnessMap=arm;m.roughness=.9;m.aoMap=arm;m.aoMapIntensity=.8;m.needsUpdate=true;}
 stoneMat.color.set(0xc4bca4);darkMat.color.set(0xa4a087);mossMat.color.set(0x647049);sculptureMat.color.set(0xa29d81);
 const pmrem=new THREE.PMREMGenerator(renderer);scene.environment=pmrem.fromEquirectangular(hdr).texture;hdr.dispose();pmrem.dispose();
 scene.traverse(o=>{if(o.isMesh&&o.material&&o.material.isMeshStandardMaterial)o.material.envMapIntensity=.42;});
});
Promise.all([runnerReady,pbrReady,imageLoad(ASSETS.environment),imageLoad(ASSETS.monster),imageLoad(ASSETS.reference),modelReady,facadeReady,fireReady]).then(([, ,env,monster,ref])=>{$('#backdrop').style.backgroundImage=`url("${env.src}")`;$('#pursuer').src=monster.src;stage.style.setProperty('--cover-image',`url("${ref.src}")`);for(const pool of [roadPool,templePool,snakes,greenPool,zoneDetails])for(const g of pool)g.traverse(o=>{if(o!==g&&!o.userData.fire&&!o.parent?.userData.fire){o.updateMatrix();o.matrixAutoUpdate=false;}});routeReadability=createRelicRouteReadability({THREE,scene,path,material:stoneMat});environmentDetail=initRelicEnvironment({THREE,scene,path,obstacles,greenPool,leafGeometry,materials:{stone:stoneMat,dark:darkMat,sculpture:sculptureMat,moss:mossMat,foliage:leafMat,fern:fernMat}});$('#loading').hidden=true;resize();updateWorld();render(.016);requestAnimationFrame(loop);}).catch(e=>{$('#loading').textContent='素材未能载入，请刷新后重试。';console.error('Asset load error',e);});






